In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
np.arange(2,4, 2)

array([2])

In [ ]:
np.zeros((3,6), dtype=np.int8)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int8)

In [ ]:
np.ones((2, 6,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [ ]:
np.eye(3, 6, -1)

array([[0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.]])

In [ ]:
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.diag([1,2, 7,5,7])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 7, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 7]])

In [ ]:
arr = np.linspace(2,3)

In [ ]:
arr =np.arange(2, 50)

In [ ]:
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
arr[-48]

np.int64(2)

In [ ]:
len(arr)

48

In [ ]:
arr.size

48

In [ ]:
a = np.array([[4,6,7,9,12], [5,9,10, 5, 10]])

In [ ]:
a[1, 0]

np.int64(5)

In [ ]:
a

array([[ 4,  6,  7,  9, 12],
       [ 5,  9, 10,  5, 10]])

In [ ]:
a[0, -1]

np.int64(12)

In [ ]:
a[-2, -1]

np.int64(12)

In [ ]:
arr = arr.reshape(6,8)

In [ ]:
arr

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr[2,6], arr[4,4], arr[4,7], arr[2,0]

(np.int64(24), np.int64(38), np.int64(41), np.int64(18))

In [ ]:
arr = arr.reshape(2,3,8)

In [ ]:
arr[0, 0, 0]

np.int64(2)

In [ ]:
arr

array([[[ 2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25]],

       [[26, 27, 28, 29, 30, 31, 32, 33],
        [34, 35, 36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47, 48, 49]]])

In [ ]:
arr[1, 0, 4], arr[0, 1, 6], arr[1, 2, 7]

(np.int64(30), np.int64(16), np.int64(49))

In [ ]:
arr[2: 5: 2]

TypeError: slice indices must be integers or None or have an __index__ method

In [ ]:
arr

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr[0:2, 3: 6], arr[2:5, 3:-2]

(array([[ 5,  6,  7],
        [13, 14, 15]]),
 array([[21, 22, 23],
        [29, 30, 31],
        [37, 38, 39]]))

In [ ]:
arr[1::2, 1::2] = 90

In [ ]:
arr[0] = 100

In [ ]:
arr[3] = [1,2,3,4,5,6,7,9]

In [ ]:
arr + 3

array([[103, 103, 103, 103, 103, 103, 103, 103],
       [  4,   5,   6,   7,   8,   9,  10,  11],
       [ 21,  22,  23,  24,  25,  26,  27,  28],
       [  4,   5,   6,   7,   8,   9,  10,  12],
       [ 37,  38,  39,  40,  41,  42,  43,  44],
       [ 45,  93,  47,  93,  49,  93,  51,  93]])

In [ ]:
arr <=10

array([[False, False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [ ]:
<, >, ==,>=, <=, !=

In [ ]:
arr+3 != 10

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [ ]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100],
       [  1,   2,   3,   4,   5,   6,   7,   8],
       [ 18,  19,  20,  21,  22,  23,  24,  25],
       [  1,   2,   3,   4,   5,   6,   7,   9],
       [ 34,  35,  36,  37,  38,  39,  40,  41],
       [ 42,  90,  44,  90,  46,  90,  48,  90]])

In [ ]:
# and or not
# & | ~

True

In [ ]:
(arr > 3) & (arr ==10)

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [ ]:
arr[(arr > 3) & (arr !=10)]

array([100, 100, 100, 100, 100, 100, 100, 100,   4,   5,   6,   7,   8,
        18,  19,  20,  21,  22,  23,  24,  25,   4,   5,   6,   7,   9,
        34,  35,  36,  37,  38,  39,  40,  41,  42,  90,  44,  90,  46,
        90,  48,  90])

In [ ]:
a

array([[ 4,  6,  7,  9, 12],
       [ 5,  9, 10,  5, 10]])

In [ ]:
mask = a>7

In [ ]:
a[a >7 ]

array([ 9, 12,  9, 10, 10])

In [ ]:
arr =np.arange(2, 50)