In [ ]:
import numpy as np

In [ ]:
# aggregation functions

In [ ]:
arr = np.arange(1, 11)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# sum
np.sum(arr)

np.int64(55)

In [ ]:
# mean
np.mean(arr)

np.float64(5.5)

In [ ]:
np.median(arr)

np.float64(5.5)

In [ ]:
np.std(arr)

np.float64(2.8722813232690143)

In [ ]:
np.var(arr)

np.float64(8.25)

In [ ]:
np.max(arr)

np.int64(10)

In [ ]:
np.min(arr)

np.int64(1)

In [ ]:
np.argmax(arr)

np.int64(9)

In [ ]:
np.argmin(arr)

np.int64(0)

In [ ]:
# universal functions

In [ ]:
# np.add()

a = np.array([1,2,3])
b = np.array([4,5,6])
np.add(a, b)

array([5, 7, 9])

In [ ]:
np.subtract(a, b)

array([-3, -3, -3])

In [ ]:
np.multiply(a, b)

array([ 4, 10, 18])

In [ ]:
np.divide(a, b)

array([0.25, 0.4 , 0.5 ])

In [ ]:
np.divmod(a, b)

(array([0, 0, 0]), array([1, 2, 3]))

In [ ]:
np.floor_divide(a, b)

array([0, 0, 0])

In [ ]:
np.remainder(a,b )

array([1, 2, 3])

In [ ]:
np.absolute(a), np.absolute(np.array([-2, 6, 4.9]))

(array([1, 2, 3]), array([2. , 6. , 4.9]))

In [ ]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [ ]:
np.cbrt(arr)

array([1.        , 1.25992105, 1.44224957, 1.58740105, 1.70997595,
       1.81712059, 1.91293118, 2.        , 2.08008382, 2.15443469])

In [ ]:
np.square(a)

array([1, 4, 9])

In [ ]:
np.less(a, b),
a = np.greater(a, b),
np.less_equal(a, b),
np.greater_equal(a, b),
np.not_equal(a, b),
np.equal(a , b)

array([[False, False, False]])

In [ ]:
out = np.empty((1,3))

In [ ]:
out
arr = arr[:3]

In [ ]:
np.add(a, b,  where=np.greater(a, b), out=out)

array([[0, 0, 0]])

array([[0., 0., 0.]])

In [ ]:
a

(array([False, False, False]),)

In [ ]:
arr, b

(array([1, 2, 3]), array([4, 5, 6]))

In [ ]:
np.add(arr, b)

array([5, 7, 9])

In [ ]:
garbage = np.empty_like(arr)

In [ ]:
np.add(arr,b, where=[True, False, True], out=garbage)

array([5, 0, 9])

In [ ]:
garbage

array([5, 0, 9])

In [ ]:
np.add.nout

1

In [ ]:
np.inf, np.nan

(inf, nan)

In [ ]:
test = np.array([np.inf, 5.7, -3.9, np.inf, np.nan])

In [ ]:
test

array([ inf,  5.7, -3.9,  inf,  nan])

In [ ]:
np.isinf(test)

array([ True, False, False,  True, False])

In [ ]:
np.isnan(test)

array([False, False, False, False,  True])

In [ ]:
np.floor(3.6), np.ceil(3.6)
# 3 3.6 4

(np.float64(3.0), np.float64(4.0))

In [ ]:
np.trunc(5.998573489574)

np.float64(5.0)

In [ ]:
# np.nan
# 3/0
np.divide(3,0)

/tmp/ipykernel_893/2227006077.py:3: RuntimeWarning: divide by zero encountered in divide
  np.divide(3,0)


np.float64(inf)

In [ ]:
np.array([[3,4,5], [5,6, np.nan]])

array([[ 3.,  4.,  5.],
       [ 5.,  6., nan]])

In [ ]:
np.array([np.inf, -(np.inf), np.nan])

array([ inf, -inf,  nan])

In [ ]:
arr = np.arange(1, 31).reshape(6,5)

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
np.sum(arr, axis=1)

array([ 15,  40,  65,  90, 115, 140])

In [ ]:
b = np.array([[[1,2,3,4,5]]])

In [ ]:
np.sum(b, axis=0)

array([[1, 2, 3, 4, 5]])

In [ ]:
b.shape

(1, 1, 5)

In [ ]:
var =arr[:3, 2:]

In [ ]:
var

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [ ]:
np.sum(var, axis=0) # 0 row

array([24, 27, 30])

In [ ]:
np.sum(var, axis=1) # 0 row  3 + 4 + 5 [0, 0] + [0, 1] + [0, 2]

array([12, 27, 42])

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
np.mean(arr, axis=1)

array([ 3.,  8., 13., 18., 23., 28.])

In [ ]:
arr[arr>3 ]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
np.where(arr>3)

(array([0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
        5, 5, 5, 5, 5]),
 array([3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4,
        0, 1, 2, 3, 4]))

In [ ]:
# 1 if arr> 4 else 0
arr[np.where(((arr > 3)| (arr==1)), True, False)]

array([ 1,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
# reshape
arr.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30]])

In [ ]:
arr.resize(1, 30)

In [ ]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [ ]:
lst = [[1,2,3], [3,4,5]]

In [ ]:
a = lst

In [ ]:
a

[[1, 2, 3], [3, 4, 5]]

In [ ]:
id(a) == id(lst)

True

In [ ]:
id(a)

137197727243840