<a href="https://colab.research.google.com/github/UdayMalviya/DataScience-Evening/blob/master/notebooks/numpy/numpy_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a = [[1,2,3], [5,6,7]]

In [4]:
# view, copy
a

[[1, 2, 3], [5, 6, 7]]

In [5]:
b = a

In [11]:
id(b) == id(a)

True

In [9]:
id(b)

134805063051648

In [10]:
id(a)

134805063051648

In [12]:
a is b

True

In [15]:
arr = np.array([1,2,3,4,5,6]) # slicing # view

In [17]:
slice_ = arr[1:4]

In [19]:
slice_[0] = 100

In [21]:
slice_, arr

(array([100,   3,   4]), array([  1, 100,   3,   4,   5,   6]))

In [23]:
slice_.base

array([  1, 100,   3,   4,   5,   6])

In [24]:
arr.base

In [25]:
# copy
## shallow copy
## deep copy

In [26]:
a

[[1, 2, 3], [5, 6, 7]]

In [27]:
b = a.copy() # shallow copy : outer obj has different address and inner obj has same address

In [29]:
b

[[1, 2, 3], [5, 6, 7]]

In [30]:
id(a) == id(b)

False

In [32]:
id(a[0]) == id(b[0])

True

In [34]:
a[0][0] = 100

In [35]:
a

[[100, 2, 3], [5, 6, 7]]

In [36]:
b

[[100, 2, 3], [5, 6, 7]]

In [37]:
# deep copy

In [38]:
import copy
b = copy.deepcopy(a)

In [40]:
id(a[0]) == id(b[0])

False

In [44]:
arr1 = arr.copy() # deep copy

In [46]:
id(arr[0]) == id(arr1[0])

True

In [48]:
arr

array([  1, 100,   3,   4,   5,   6])

In [49]:
arr1.base

In [50]:
# View : parent, child
# shallow copy : parent, child
# deep copy : parent, child

In [52]:
# adding a new axis

In [54]:
arr.reshape(1, -1)

array([[  1, 100,   3,   4,   5,   6]])

In [56]:
arr[:, np.newaxis]

(6, 1)

In [64]:
ar = arr[np.newaxis, np.newaxis, np.newaxis, :].reshape(1,1, 3,2)

In [65]:
ar

array([[[[  1, 100],
         [  3,   4],
         [  5,   6]]]])

In [66]:
ar.squeeze()

array([[  1, 100],
       [  3,   4],
       [  5,   6]])

In [70]:
# squeeze resolve dimensions 1
np.zeros((1,2,1,1,1)).squeeze()

array([0., 0.])

In [72]:
arr.resize(2,3)

In [73]:
arr

array([[  1, 100,   3],
       [  4,   5,   6]])

In [76]:
a = arr.reshape(3,2)

In [79]:
a[0,0]= 6

In [80]:
arr

array([[  6, 100,   3],
       [  4,   5,   6]])

In [81]:
a

array([[  6, 100],
       [  3,   4],
       [  5,   6]])

In [83]:
a.shape, arr.shape

((3, 2), (2, 3))

In [85]:
a * 4

array([[ 24, 400],
       [ 12,  16],
       [ 20,  24]])

In [86]:
a

array([[  6, 100],
       [  3,   4],
       [  5,   6]])

In [87]:
a * a

array([[   36, 10000],
       [    9,    16],
       [   25,    36]])

In [94]:
b= np.array([[1],[2],[3]])

In [ ]:
(1,3)

In [96]:
a  + b

array([[  7, 101],
       [  5,   6],
       [  8,   9]])

In [97]:
a.shape, b.shape

((3, 2), (3, 1))

In [100]:
a * arr

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [99]:
a.shape, arr.shape

((3, 2), (2, 3))

In [101]:
# matrix

In [102]:
a  + a*2

array([[ 18, 300],
       [  9,  12],
       [ 15,  18]])

In [103]:
# a * arr # element wise multipy ERROR
# dot product
np.dot(a,arr)

array([[ 436, 1100,  618],
       [  34,  320,   33],
       [  54,  530,   51]])

In [104]:
a @ arr

array([[ 436, 1100,  618],
       [  34,  320,   33],
       [  54,  530,   51]])

In [105]:
a.shape, arr.shape

((3, 2), (2, 3))

In [106]:
arr @ a

array([[ 351, 1018],
       [  69,  456]])

In [107]:
a

array([[  6, 100],
       [  3,   4],
       [  5,   6]])

In [108]:
arr

array([[  6, 100,   3],
       [  4,   5,   6]])

In [109]:
a @ arr

array([[ 436, 1100,  618],
       [  34,  320,   33],
       [  54,  530,   51]])

In [113]:
np.arange(1,7).reshape(3, 2) @ np.arange(1,7).reshape(2,3)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [116]:
np.arange(1,7).reshape(2,3, order="C") # Row major


array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
np.arange(1,7).reshape(2,3, order="F") # col major

array([[1, 3, 5],
       [2, 4, 6]])

In [118]:
np.arange(1,7).reshape(2,3, order="A") # Any

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
# Transpose  row col
arr.T

array([[  6,   4],
       [100,   5],
       [  3,   6]])

In [124]:
# inverse of matrix
np.linalg.inv(np.array([[1,2], [3,4]]))

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
2x + 3y = 5
3x + 2y = 6 #y= -2

In [126]:
np.linalg.solve(np.array([[2,3], [3,2]]), np.array([[5], [6]]))


array([[1.6],
       [0.6]])

In [128]:
(2* 1.6 ) + (3 * 0.6)

5.0