In [2]:
import numpy as np

In [4]:
# array creation

lst = [1,2,3]

In [6]:
type(np.array(lst))

numpy.ndarray

In [7]:
np.array(lst)

array([1, 2, 3])

In [11]:
ls = list(range(500000))

In [14]:
%%timeit
l = []
for i in ls:
    l.append(i*2)

58.1 ms ± 1.49 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [15]:
%%timeit
np.array(ls)*2

39.9 ms ± 2.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [40]:
a =np.array([[1,2,3], [5,6,7]])

In [28]:
set(range(1,10,2) )

{1, 3, 5, 7, 9}

In [31]:
np.arange(3,10, 4)

array([3, 7])

In [37]:
#shape, size, ndim,

In [39]:
# shape
arr.shape

(3,)

In [42]:
a.shape, a

((2, 3),
 array([[1, 2, 3],
        [5, 6, 7]]))

In [44]:
# size
a.size, arr.size

(6, 3)

In [45]:
a.ndim

2

In [46]:
a

array([[1, 2, 3],
       [5, 6, 7]])

In [53]:
arr.dtype

dtype('int64')

In [52]:
np.array(4).dtype

dtype('int64')

In [51]:
# 0D numpy scaler
# 1D vector
# 2D Matrix
# 3D+ Tensor 

In [55]:
np.array([3.6,6.7]).dtype

dtype('float64')

In [57]:
np.array([True, False]).dtype

dtype('bool')

In [59]:
np.array(['ABD', 'B'])

array(['ABD', 'B'], dtype='<U3')

In [ ]:
# np.array
# np.arange
# shape, size, ndim, dtype 